// <auto-generated />
namespace PersonalFinancesManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class syncAzure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(syncAzure));
        
        string IMigrationMetadata.Id
        {
            get { return "201303142300050_syncAzure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
